[programs.devnet]
gif_portal = "5xAoCBhH8WbUiauQVyaSUorsbsfZ7VjL1oRTUeYJfb3K"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/joaquimley/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
